version: "3.3"
services:
  mongodb:
    image: tutum/mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_USER: "omnistack"
      MONGODB_DATABASE: "omnistack"
      MONGODB_PASS: "omnistack"
